Include requirements.txt in the release distribution
The 'requirements.txt' file is currently missing from the release
distribution.

This causes pip to fail when installing 'tripleo-helper' with the
following error:

IOError: [Errno 2] No such file or directory:
'/tmp/pip-build-jw81Dm/tripleo-helper/requirements.txt'

This commit adds the 'requirements.txt' file in the release.

Change-Id: I4c687006526fd4ed18cee65922a076cae832a467